name: RankTankPlugin
main: com.briangershon.ranktank.App
description: A Minecraft plugin for assigning players a rank and showing top ranks on a scoreboard.
version: ${project.version}
api-version: 1.13
